### ISSUE TITLE
Anpassung yaml Optionen & Erläuterung in der index page

### ISSUE THREAD

**Issue by jan-abel-inwt** [INWT/inwt-quarto-template-report#9]
- [x] folgende Optionen sollen von `_extension.yml` zu `_quarto.yml` verschoben werden:

```
title: "Template Report"
subtitle: "optional subtitle"
author: 
        name: Maxine Mustermensch
        email: maxine.mustermensch@inwt-statistics.de
        affiliation: inwt
repo-url: https://github.com/INWT/inwt-quarto-template-report
repo-actions: [edit, issue, source]
```

- [ ] ~template link in `page-footer`~ - doch nicht
- [ ]  Anpassung index-page
